version: "3"
services:
  web:
    image: adamwebb/get-started:part1
    deploy:
      replicas: 5
      resources:
        cpus: "0.1"
        memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet: